(function(){
var $=function(id){return document.getElementById(id)},E={home:$("home"),game:$("game"),name:$("name"),create:$("create"),openJoin:$("openJoin"),joinBox:$("joinBox"),room:$("roomInput"),join:$("join"),net:$("net"),code:$("code"),role:$("role"),copyCode:$("copyCode"),copyLink:$("copyLink"),players:$("players"),status:$("status"),leave:$("leave"),title:$("title"),count:$("count"),last:$("last"),card:$("card"),draw:$("draw"),bingo:$("bingo"),history:$("history"),winner:$("winner"),shadowWrap:$("shadowWrap"),shadowTitle:$("shadowTitle"),shadowCard:$("shadowCard"),toast:$("toast"),modal:$("modal"),modalText:$("modalText"),closeModal:$("closeModal"),install:$("installApp"),voiceToggle:$("voiceToggle"),winnerName:$("winnerName"),winnerCalls:$("winnerCalls"),confettiLayer:$("confettiLayer"),replayBtn:$("replayBtn"),replayInline:$("replayInline"),replayArea:$("replayArea"),roundState:$("roundState"),roundProgressFill:$("roundProgressFill"),opponentMarkCount:$("opponentMarkCount")};
 var S={host:false,code:"",name:"",peer:null,hostConn:null,conns:new Map(),players:new Map(),card:[],marked:new Set([12]),called:[],bag:[],winner:null,id:"",joined:false,autoTimer:null,countdownTimer:null,autoRunning:false,nextDrawAt:0,voiceOn:localStorage.getItem("bingoVoice")!=="off",lastSpoken:""};
var deferredInstallPrompt=null,isStandalone=window.matchMedia&&window.matchMedia("(display-mode: standalone)").matches||window.navigator.standalone===true;
var invite=(new URLSearchParams(location.search).get("room")||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);if(invite){E.room.value=invite;E.joinBox.classList.remove("hidden")}var sn=localStorage.getItem("bingoNerdoraName");if(sn)E.name.value=sn;
function toast(t){E.toast.textContent=t;E.toast.classList.add("show");setTimeout(function(){E.toast.classList.remove("show")},2200)}
function net(t,ok){E.net.textContent=(ok?"● ":"○ ")+t;E.net.style.color=ok?"#7ef0b5":""}
function clean(){return E.name.value.trim().replace(/[<>]/g,"").slice(0,24)}
function code(){var c="ABCDEFGHJKLMNPQRSTUVWXYZ23456789",s="";for(var i=0;i<6;i++)s+=c[Math.floor(Math.random()*c.length)];return s}
function pid(c){return "nerdora-bingo-"+c.toLowerCase()}
function rid(){return Math.random().toString(36).slice(2,10)}
function sh(a){for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),x=a[i];a[i]=a[j];a[j]=x}return a}
function makeCard(){var ranges=[[1,15],[16,30],[31,45],[46,60],[61,75]],c=[];for(var col=0;col<5;col++){var a=[];for(var n=ranges[col][0];n<=ranges[col][1];n++)a.push(n);sh(a);for(var r=0;r<5;r++)c[r*5+col]=a[r]}c[12]=0;return c}
function bag(){return sh(Array.from({length:75},function(_,i){return i+1}))}
function letter(n){return n<=15?"B":n<=30?"I":n<=45?"N":n<=60?"G":"O"}
function tone(n){return n<=15?"tone-b":n<=30?"tone-i":n<=45?"tone-n":n<=60?"tone-g":"tone-o"}
function label(n){if(!n)return"LIVRE";return letter(n)+n}
function getPtVoice(){if(!("speechSynthesis" in window))return null;var vs=window.speechSynthesis.getVoices().filter(function(v){return (v.lang||"").toLowerCase().indexOf("pt")===0});if(!vs.length)return null;function score(v){var n=(v.name||"").toLowerCase(),l=(v.lang||"").toLowerCase(),s=0;if(l==="pt-br")s+=100;if(/google|natural|neural|premium|microsoft|online/.test(n))s+=60;if(/female|feminina|francisca|luciana|maria|camila|fernanda/.test(n))s+=12;if(v.localService===false)s+=8;return s}vs.sort(function(x,y){return score(y)-score(x)});return vs[0]}
function speakText(text,opts){if(!S.voiceOn||!("speechSynthesis" in window))return;opts=opts||{};try{var u=new SpeechSynthesisUtterance(text);u.lang="pt-BR";u.rate=opts.rate||.82;u.pitch=opts.pitch||.96;u.volume=1;var v=getPtVoice();if(v)u.voice=v;window.speechSynthesis.cancel();window.speechSynthesis.resume();setTimeout(function(){try{window.speechSynthesis.speak(u)}catch(e){}},70)}catch(e){}}
function speakBall(n){if(!n)return;var lab=label(n);if(lab===S.lastSpoken)return;S.lastSpoken=lab;var names={B:"Bê",I:"I",N:"Ene",G:"Gê",O:"Ó"};speakText(names[letter(n)]+". "+n+".",{rate:.80,pitch:.94})}
function refreshVoiceButton(){if(!E.voiceToggle)return;E.voiceToggle.textContent=S.voiceOn?"🔊 Narração":"🔇 Narração";E.voiceToggle.classList.toggle("voiceOff",!S.voiceOn)}
function esc(s){return String(s).replace(/[&<>"']/g,function(c){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]})}
function renderCard(){E.card.innerHTML="";S.card.forEach(function(n,i){var marked=S.marked.has(i),called=i===12||S.called.indexOf(n)>=0,b=document.createElement("button");b.className="cell"+(marked?" marked":"")+(marked&&!called?" pending":"")+(i===12?" free":"");if(i===12)b.innerHTML='<span class="nerdoraMark" aria-label="Nerdora">N</span>';else b.textContent=n;b.onclick=function(){if(i===12)return;S.marked.has(i)?S.marked.delete(i):S.marked.add(i);renderCard();renderBingoState();sendMarks()};E.card.appendChild(b)});renderBingoState()}
function renderHistory(){E.history.innerHTML="";var latest=S.called.length?S.called[0]:null;S.called.forEach(function(n,idx){var d=document.createElement("div");d.className="hball "+tone(n)+(idx===0?" current":"");d.dataset.order=String(idx);d.innerHTML='<span class="hletter">'+letter(n)+'</span><span class="hnum">'+n+'</span>';E.history.appendChild(d)});var l=latest;E.last.textContent=l?label(l):"—";E.last.className="ball"+(l?" "+tone(l):"");if(l){void E.last.offsetWidth;E.last.classList.add("ballPop");speakBall(l)}E.count.textContent=S.called.length+" de 75 bolas";if(E.roundProgressFill)E.roundProgressFill.style.width=Math.min(100,(S.called.length/75)*100)+"%";E.title.textContent=S.winner?"Partida encerrada":(l?"Última bola: "+label(l):"Aguardando início");renderCard();renderAutoState()}
function renderPlayers(){E.players.innerHTML="";Array.from(S.players.values()).forEach(function(p){var d=document.createElement("div");d.className="player";d.innerHTML='<div class="avatar">'+esc((p.name||"?")[0].toUpperCase())+'</div><span>'+esc(p.name)+(p.id===S.id?' <small>(você)</small>':"")+(p.host?' <small>★ host</small>':"")+"</span>";E.players.appendChild(d)});renderShadow()}
function renderShadow(){var other=Array.from(S.players.values()).find(function(p){return p.id!==S.id});if(!other){E.shadowWrap.classList.add("hidden");while(E.shadowCard.firstChild)E.shadowCard.removeChild(E.shadowCard.firstChild);if(E.opponentMarkCount)E.opponentMarkCount.textContent="0 marcações";return}E.shadowWrap.classList.remove("hidden");if(E.shadowTitle)E.shadowTitle.textContent="Cartela de "+(other.name||"oponente");while(E.shadowCard.firstChild)E.shadowCard.removeChild(E.shadowCard.firstChild);var marks=new Set(Array.isArray(other.marked)?other.marked:[]),markedCount=0,ns="http://www.w3.org/2000/svg";for(var row=0;row<5;row++){for(var col=0;col<5;col++){var idx=row*5+col,isFree=idx===12,isMarked=!isFree&&marks.has(idx);if(isMarked)markedCount++;var rect=document.createElementNS(ns,"rect");rect.setAttribute("x",String(2+col*21));rect.setAttribute("y",String(2+row*21));rect.setAttribute("width","18");rect.setAttribute("height","18");rect.setAttribute("rx","4");rect.setAttribute("class","opponentMiniRectV22"+(isFree?" free":"")+(isMarked?" marked":""));rect.setAttribute("data-pos",String(idx));E.shadowCard.appendChild(rect)}}if(E.opponentMarkCount)E.opponentMarkCount.textContent=markedCount+(markedCount===1?" marcação":" marcações")}
function lines(){var a=[];for(var r=0;r<5;r++){var x=[];for(var c=0;c<5;c++)x.push(r*5+c);a.push(x)}for(var c=0;c<5;c++){var y=[];for(var r=0;r<5;r++)y.push(r*5+c);a.push(y)}a.push([0,6,12,18,24],[4,8,12,16,20]);return a}
function has(marked){return lines().some(function(l){return l.every(function(i){return marked.has(i)})})}
function allMarkedCalled(){for(var i of S.marked){if(i!==12&&S.called.indexOf(S.card[i])<0)return false}return true}
function bingoReady(){return !S.winner&&has(S.marked)&&allMarkedCalled()}
function renderBingoState(){var ok=bingoReady();E.bingo.classList.toggle("hidden",!ok);E.bingo.disabled=!ok}
function valid(card,marked){var set=new Set(marked);set.add(12);if(!has(set))return false;for(var i of set){if(i!==12&&S.called.indexOf(card[i])<0)return false}return true}
function sendMarks(){var marks=Array.from(S.marked);if(S.host){var me=S.players.get(S.id);if(me){me.marked=marks;S.players.set(S.id,me);sync()}}else if(S.hostConn&&S.hostConn.open){S.hostConn.send({type:"mark",id:S.id,marked:marks})}}
function publicPlayers(){return Array.from(S.players.values()).map(function(p){return{id:p.id,name:p.name,host:p.host,marked:Array.isArray(p.marked)?p.marked:[12]}})}
function broadcast(m){S.conns.forEach(function(c){if(c.open)try{c.send(m)}catch(e){}})}
function sync(){if(S.winner&&S.host&&S.autoRunning){clearInterval(S.autoTimer);clearInterval(S.countdownTimer);S.autoTimer=null;S.countdownTimer=null;S.autoRunning=false;S.nextDrawAt=0}var ps=publicPlayers();broadcast({type:"state",called:S.called,calledOrder:"newest-first",winner:S.winner,players:ps,autoRunning:S.autoRunning,nextDrawAt:S.nextDrawAt});renderHistory();renderPlayers();renderWinner();renderBingoState()}
function launchConfetti(){if(!E.confettiLayer)return;E.confettiLayer.innerHTML="";var tones=["#43d9ff","#a66bff","#ff58b8","#58e7a0","#ffad55","#ffffff"];for(var i=0;i<52;i++){var p=document.createElement("i");p.className="confettiPiece";p.style.left=(Math.random()*100)+"%";p.style.background=tones[i%tones.length];p.style.setProperty("--dur",(2.8+Math.random()*2.2)+"s");p.style.setProperty("--rot",(Math.random()*360)+"deg");p.style.setProperty("--drift",(-90+Math.random()*180)+"px");p.style.animationDelay=(Math.random()*.7)+"s";E.confettiLayer.appendChild(p)}}
function resetRoundUi(){S.lastSpoken="";if(E.modal){E.modal.classList.add("hidden");E.modal.dataset.w=""}if(E.confettiLayer)E.confettiLayer.innerHTML="";if(E.replayArea)E.replayArea.classList.add("hidden");if(E.replayBtn){E.replayBtn.disabled=false;E.replayBtn.textContent="🔄 Jogar novamente"}if(E.replayInline){E.replayInline.disabled=false;E.replayInline.textContent="🔄 Jogar novamente"}}
function restartRound(){if(!S.host)return;clearInterval(S.autoTimer);clearInterval(S.countdownTimer);S.autoTimer=null;S.countdownTimer=null;S.autoRunning=false;S.nextDrawAt=0;S.called=[];S.bag=bag();S.winner=null;S.lastSpoken="";S.card=makeCard();S.marked=new Set([12]);var me=S.players.get(S.id);if(me){me.card=S.card;me.marked=[12];S.players.set(S.id,me)}var deliveries=[];Array.from(S.players.values()).forEach(function(p){if(p.id===S.id)return;var nc=makeCard();p.card=nc;p.marked=[12];S.players.set(p.id,p);deliveries.push({peer:p.peer,card:nc})});var ps=publicPlayers();deliveries.forEach(function(item){var conn=S.conns.get(item.peer);if(conn&&conn.open)try{conn.send({type:"new_round",card:item.card,called:[],calledOrder:"newest-first",winner:null,players:ps,autoRunning:false,nextDrawAt:0})}catch(e){}});resetRoundUi();renderCard();renderHistory();renderPlayers();renderWinner();renderAutoState();E.status.textContent="Nova partida pronta. Inicie o sorteio quando quiser.";sync();toast("Nova partida criada sem sair da sala.")}
function requestReplay(){if(S.host){restartRound();return}if(S.hostConn&&S.hostConn.open){S.hostConn.send({type:"restart_request",id:S.id,name:S.name});if(E.replayBtn){E.replayBtn.disabled=true;E.replayBtn.textContent="Pedido enviado ✓"}if(E.replayInline){E.replayInline.disabled=true;E.replayInline.textContent="Pedido enviado ✓"}toast("Pedido de nova partida enviado ao anfitrião.")}}
function renderWinner(){if(!S.winner){E.winner.classList.add("hidden");if(E.replayArea)E.replayArea.classList.add("hidden");E.draw.disabled=false;renderBingoState();return}E.winner.classList.remove("hidden");E.winner.textContent="🏆 "+S.winner.name+" fez BINGO!";if(E.replayArea)E.replayArea.classList.remove("hidden");if(E.replayBtn){E.replayBtn.disabled=false;E.replayBtn.textContent=S.host?"🔄 Jogar novamente":"🔄 Pedir nova partida"}if(E.replayInline){E.replayInline.disabled=false;E.replayInline.textContent=S.host?"🔄 Jogar novamente":"🔄 Pedir nova partida"}E.draw.disabled=true;E.bingo.classList.add("hidden");E.status.textContent="Partida encerrada.";E.modalText.textContent=S.winner.name+" completou uma linha válida e venceu a partida.";if(E.winnerName)E.winnerName.textContent=S.winner.name+" venceu!";if(E.winnerCalls)E.winnerCalls.textContent=String(S.called.length);if(E.modal.dataset.w!==S.winner.id){E.modal.dataset.w=S.winner.id;launchConfetti();E.modal.classList.remove("hidden");S.lastSpoken="";speakText("Bingo! "+S.winner.name+" venceu a partida!",{rate:.84,pitch:1.02})}}
function hostConn(c){c.on("open",function(){S.conns.set(c.peer,c)});c.on("data",function(d){if(!d||typeof d!=="object")return;if(d.type==="join"){var id=String(d.id||rid()).slice(0,20),nm=String(d.name||"Jogador").slice(0,24),card=Array.isArray(d.card)&&d.card.length===25?d.card:makeCard();S.players.set(id,{id:id,name:nm,host:false,peer:c.peer,card:card,marked:[12]});c.send({type:"welcome",called:S.called,calledOrder:"newest-first",winner:S.winner,players:Array.from(S.players.values()).map(function(p){return{id:p.id,name:p.name,host:p.host,marked:Array.isArray(p.marked)?p.marked:[12]}}),autoRunning:S.autoRunning,nextDrawAt:S.nextDrawAt});sync()}if(d.type==="mark"){var mp=S.players.get(d.id),mm=Array.isArray(d.marked)?d.marked.filter(function(i){return Number.isInteger(i)&&i>=0&&i<25}):[12];if(mp){mp.marked=mm;S.players.set(d.id,mp);sync()}}if(d.type==="restart_request"){var rp=S.players.get(d.id);toast((rp&&rp.name?rp.name:(d.name||"Um jogador"))+" quer jogar novamente.")}if(d.type==="claim"){var p=S.players.get(d.id),m=Array.isArray(d.marked)?d.marked:[];if(p&&!S.winner&&valid(p.card,m)){S.winner={id:p.id,name:p.name};sync()}else c.send({type:"reject"})}});c.on("close",function(){var p=Array.from(S.players.values()).find(function(x){return x.peer===c.peer});if(p)S.players.delete(p.id);S.conns.delete(c.peer);sync()})}
function clientMsg(d){if(!d||typeof d!=="object")return;if(d.type==="new_round"){S.card=Array.isArray(d.card)&&d.card.length===25?d.card:makeCard();S.marked=new Set([12]);S.called=[];S.winner=null;S.autoRunning=false;S.nextDrawAt=0;S.lastSpoken="";S.players=new Map((d.players||[]).map(function(p){return[p.id,p]}));var self=S.players.get(S.id);if(self){self.marked=[12];S.players.set(S.id,self)}resetRoundUi();renderCard();renderHistory();renderPlayers();renderWinner();renderAutoState();E.status.textContent="Nova partida pronta. Aguardando o anfitrião iniciar.";toast("Nova partida! Você recebeu uma cartela nova.");return}if(d.type==="welcome"||d.type==="state"){if(d.type==="welcome"){S.joined=true;E.status.textContent="Conectado ao anfitrião.";net("conectado",true)}S.called=Array.isArray(d.called)?d.called.slice():[];if(d.calledOrder!=="newest-first")S.called.reverse();S.winner=d.winner||null;S.autoRunning=!!d.autoRunning;S.nextDrawAt=Number(d.nextDrawAt)||0;S.players=new Map((d.players||[]).map(function(p){return[p.id,p]}));renderHistory();renderPlayers();renderWinner();renderAutoState();renderBingoState()}if(d.type==="reject")toast("O Bingo ainda não é válido.")}
function gameUI(){E.code.textContent=S.code;E.role.textContent=S.host?"Você é o anfitrião":"Você entrou como jogador";E.draw.classList.toggle("hidden",!S.host);E.draw.textContent="Iniciar sorteio automático";E.bingo.classList.add("hidden");E.status.textContent=S.host?"Sala criada. Inicie quando todos entrarem.":"Conectando ao anfitrião...";S.card=makeCard();S.marked=new Set([12]);renderCard();renderHistory();renderPlayers();renderBingoState();E.home.classList.add("hidden");E.game.classList.remove("hidden");E.game.classList.remove("sceneEnter");void E.game.offsetWidth;E.game.classList.add("sceneEnter");setTimeout(function(){E.game.classList.remove("sceneEnter")},520)}
function createPeer(){var p=new Peer(pid(S.code),{debug:0});S.peer=p;p.on("open",function(){net("sala online",true);E.status.textContent="Sala online. Convide seus amigos."});p.on("connection",hostConn);p.on("error",function(e){if(e&&e.type==="unavailable-id"){p.destroy();S.code=code();E.code.textContent=S.code;createPeer()}else{net("erro");E.status.textContent="Erro de conexão."}})}
function createRoom(){if(S.voiceOn&&"speechSynthesis" in window){try{window.speechSynthesis.resume()}catch(e){}}var nm=clean();if(!nm){toast("Digite seu nome.");return}localStorage.setItem("bingoNerdoraName",nm);S.host=true;S.name=nm;S.code=code();S.id="host-"+rid();S.called=[];S.bag=bag();S.winner=null;S.card=makeCard();S.players=new Map([[S.id,{id:S.id,name:nm,host:true,card:S.card,marked:[12]}]]);gameUI();net("abrindo sala");createPeer()}
function joinRoom(){if(S.voiceOn&&"speechSynthesis" in window){try{window.speechSynthesis.resume()}catch(e){}}var nm=clean(),cd=E.room.value.trim().toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);if(!nm){toast("Digite seu nome.");return}if(cd.length!==6){toast("Digite o código de 6 caracteres.");return}localStorage.setItem("bingoNerdoraName",nm);S.host=false;S.name=nm;S.code=cd;S.id="p-"+rid();S.called=[];S.winner=null;S.card=makeCard();S.players=new Map([[S.id,{id:S.id,name:nm,host:false,marked:[12]}]]);gameUI();net("conectando");var p=new Peer(undefined,{debug:0});S.peer=p;p.on("open",function(){var c=p.connect(pid(cd),{reliable:true});S.hostConn=c;c.on("open",function(){c.send({type:"join",id:S.id,name:S.name,card:S.card,marked:Array.from(S.marked)});E.status.textContent="Entrando na sala..."});c.on("data",clientMsg);c.on("close",function(){net("host desconectado");E.status.textContent="O anfitrião saiu da sala."});setTimeout(function(){if(!S.joined){net("não conectado");E.status.textContent="Sala não encontrada ou host offline."}},8000)});p.on("error",function(){net("erro");E.status.textContent="Falha de conexão."})}
function updateCountdown(){if(S.winner)return;if(S.autoRunning&&S.nextDrawAt){var left=Math.max(0,Math.ceil((S.nextDrawAt-Date.now())/1000));E.status.textContent="Sorteio automático ativo • próxima bola em "+left+"s"}else if(S.host){E.status.textContent=S.called.length?"Sorteio pausado.":"Sala pronta. Inicie o sorteio quando quiser."}else if(S.joined){E.status.textContent=S.called.length?"Sorteio pausado pelo anfitrião.":"Aguardando o anfitrião iniciar."}}
function renderAutoState(){if(S.host){E.draw.textContent=S.autoRunning?"Pausar sorteio":"Iniciar sorteio automático"}else{clearInterval(S.countdownTimer);S.countdownTimer=null;if(S.autoRunning&&!S.winner)S.countdownTimer=setInterval(updateCountdown,250)}if(E.roundState){E.roundState.textContent=S.winner?"Encerrada":(S.autoRunning?"Sorteio ativo":(S.called.length?"Pausado":"Aguardando"));E.roundState.classList.toggle("active",!!S.autoRunning&&!S.winner);E.roundState.classList.toggle("ended",!!S.winner)}updateCountdown()}
function draw(){if(!S.host||S.winner)return;if(!S.bag.length){stopAuto(true);toast("Todas as bolas foram sorteadas.");return}S.called.unshift(S.bag.pop());S.nextDrawAt=S.autoRunning?Date.now()+7000:0;sync()}
function startAuto(){if(!S.host||S.winner||S.autoRunning)return;if(S.voiceOn&&"speechSynthesis" in window){try{window.speechSynthesis.resume()}catch(e){}}S.autoRunning=true;S.nextDrawAt=Date.now()+7000;clearInterval(S.autoTimer);clearInterval(S.countdownTimer);S.autoTimer=setInterval(draw,7000);S.countdownTimer=setInterval(updateCountdown,250);renderAutoState();sync()}
function stopAuto(announce){clearInterval(S.autoTimer);clearInterval(S.countdownTimer);S.autoTimer=null;S.countdownTimer=null;S.autoRunning=false;S.nextDrawAt=0;renderAutoState();if(S.host)sync();if(announce)toast("Sorteio automático pausado.")}
function toggleAuto(){S.autoRunning?stopAuto(true):startAuto()}
function bingo(){if(S.winner)return;if(!bingoReady()){toast("Complete uma linha e aguarde todas as marcações saírem.");return}if(S.host){if(valid(S.card,Array.from(S.marked))){S.winner={id:S.id,name:S.name};sync()}}else if(S.hostConn&&S.hostConn.open)S.hostConn.send({type:"claim",id:S.id,marked:Array.from(S.marked)})}
function copy(t,msg){if(navigator.clipboard)navigator.clipboard.writeText(t).then(function(){toast(msg)}).catch(function(){prompt("Copie:",t)});else prompt("Copie:",t)}
function setupParallax(){var root=document.documentElement,raf=0,px=0,py=0,sy=0,reduced=window.matchMedia&&window.matchMedia("(prefers-reduced-motion: reduce)").matches;if(reduced)return;function apply(){raf=0;root.style.setProperty("--px",px.toFixed(1)+"px");root.style.setProperty("--py",py.toFixed(1)+"px");root.style.setProperty("--scroll-py",sy.toFixed(1)+"px")}function request(){if(!raf)raf=requestAnimationFrame(apply)}window.addEventListener("pointermove",function(e){px=((e.clientX/window.innerWidth)-.5)*18;py=((e.clientY/window.innerHeight)-.5)*12;request()},{passive:true});window.addEventListener("scroll",function(){sy=Math.min(18,window.scrollY*.025);request()},{passive:true});window.addEventListener("deviceorientation",function(e){if(typeof e.gamma!=="number"||typeof e.beta!=="number")return;px=Math.max(-11,Math.min(11,e.gamma*.35));py=Math.max(-8,Math.min(8,(e.beta-45)*.12));request()},{passive:true})}
function setupInstall(){if(!E.install)return;if(isStandalone)E.install.classList.add("hidden");else setTimeout(function(){if(!isStandalone)E.install.classList.remove("hidden")},2200);window.addEventListener("beforeinstallprompt",function(e){e.preventDefault();deferredInstallPrompt=e;E.install.classList.remove("hidden")});window.addEventListener("appinstalled",function(){deferredInstallPrompt=null;E.install.classList.add("hidden");toast("Bingo Nerdora instalado no celular!")});E.install.onclick=async function(){if(deferredInstallPrompt){deferredInstallPrompt.prompt();try{await deferredInstallPrompt.userChoice}catch(e){}deferredInstallPrompt=null;E.install.classList.add("hidden")}else{toast("No Chrome, toque em ⋮ e escolha “Instalar app” ou “Adicionar à tela inicial”.")}}}
function setupPwa(){if("serviceWorker" in navigator){window.addEventListener("load",function(){navigator.serviceWorker.register("./sw.js").catch(function(){})})}}
function setupVoice(){refreshVoiceButton();if(!E.voiceToggle)return;E.voiceToggle.onclick=function(){S.voiceOn=!S.voiceOn;localStorage.setItem("bingoVoice",S.voiceOn?"on":"off");if(!S.voiceOn&&"speechSynthesis" in window)window.speechSynthesis.cancel();refreshVoiceButton();if(S.voiceOn){S.lastSpoken="";speakText("Narração Nerdora ativada. Boa sorte!",{rate:.84,pitch:.98})}};if("speechSynthesis" in window){window.speechSynthesis.getVoices();window.speechSynthesis.onvoiceschanged=function(){window.speechSynthesis.getVoices()}}}
setupParallax();setupInstall();setupPwa();setupVoice();
E.openJoin.onclick=function(){E.joinBox.classList.toggle("hidden")};E.create.onclick=createRoom;E.join.onclick=joinRoom;E.draw.onclick=toggleAuto;E.bingo.onclick=bingo;E.leave.onclick=function(){try{S.peer&&S.peer.destroy()}catch(e){}location.href=location.pathname};E.copyCode.onclick=function(){copy(S.code,"Código copiado.")};E.copyLink.onclick=function(){var u=new URL(location.href);u.search="";u.searchParams.set("room",S.code);copy(u.toString(),"Convite copiado.")};E.closeModal.onclick=function(){E.modal.classList.add("hidden")};if(E.replayBtn)E.replayBtn.onclick=requestReplay;if(E.replayInline)E.replayInline.onclick=requestReplay;E.room.onkeydown=function(e){if(e.key==="Enter")joinRoom()};window.addEventListener("beforeunload",function(){clearInterval(S.autoTimer);clearInterval(S.countdownTimer);try{S.peer&&S.peer.destroy()}catch(e){}});})();